use_frameworks!

platform :ios, '9.0'

target 'IWExtendUI_Example' do
  pod 'IQKeyboardManager'
  pod 'IWExtendUI', :path => '../'

  target 'IWExtendUI_Tests' do
    inherit! :search_paths

    
  end
end
